import '../scene/a_appstate.js'
import '../scene/a_switcher.js'
import '../scene/b_fov_controls.js'
import '../scene/b_grabworld.js'
import '../scene/b_orbit_controls.js'
import '../scene/b_sky.js'
import '../scene/b_stereofx.js'
import '../scene/g_button.js'
import '../scene/p_3dmode.js'
import '../scene/p_hello.js'
import '../scene/p_play.js'

import '../scene/setup.ts'
